import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, CircleAlert, DollarSign, Plus, SlidersHorizontal, TrendingDown, TrendingUp, Users } from 'lucide-react'
import { calculatePayroll, calculateSummary, profit } from '../entities/calculations'
import type { Employee, Shift, Transaction } from '../entities/types'
import { rubles } from '../shared/money'
import { connectTelegramBot, createPickupPoint, createTelegramPairingCode, disconnectTelegramBot, getTelegramIntegration, type TelegramIntegrationInfo } from '../services/manual'

const employees:Employee[]=[{id:'alex',fullName:'Александр',phone:'+7 928 000-00-01',pickupPointIds:['p1'],paymentType:'SHIFT',rateKopecks:220000,status:'ACTIVE'},{id:'max',fullName:'Максим',phone:'+7 928 000-00-02',pickupPointIds:['p1'],paymentType:'HOURLY',rateKopecks:25000,status:'ACTIVE'}]
const shifts:Shift[]=[{id:'s1',employeeId:'alex',pickupPointId:'p1',startsAt:'2026-09-01T08:00:00+03:00',endsAt:'2026-09-01T22:00:00+03:00',actualStartsAt:'2026-09-01T08:02:00+03:00',actualEndsAt:'2026-09-01T22:00:00+03:00',status:'COMPLETED'},{id:'s2',employeeId:'max',pickupPointId:'p1',startsAt:'2026-09-02T08:00:00+03:00',endsAt:'2026-09-02T22:00:00+03:00',status:'PLANNED'},{id:'s3',employeeId:'alex',pickupPointId:'p1',startsAt:'2026-09-03T08:00:00+03:00',endsAt:'2026-09-03T22:00:00+03:00',status:'PLANNED'}]
const transactions:Transaction[]=[{id:'i1',kind:'INCOME',date:'2026-09-01',pickupPointId:'p1',category:'Wildberries',amountKopecks:30738100},{id:'e1',kind:'EXPENSE',date:'2026-09-01',pickupPointId:'p1',category:'Аренда',amountKopecks:6946200},{id:'e2',kind:'EXPENSE',date:'2026-09-02',pickupPointId:'p1',category:'Расходники',amountKopecks:3119800}]
const status:Record<string,string>={PLANNED:'Запланирована',ON_DUTY:'На смене',COMPLETED:'Завершена',REPLACED:'Замена',NO_SHOW:'Не вышел'}
function Title({title,children}:{title:string;children?:React.ReactNode}){return <div className="mb-5 flex flex-wrap items-center justify-between gap-3 sm:mb-6"><div className="min-w-0"><h1 className="text-xl font-bold tracking-tight sm:text-2xl">{title}</h1><p className="mt-1 text-sm text-slate-500">Кооперативная 93 · Сентябрь 2026</p></div>{children}</div>}
function Metric({label,value,icon:Icon,tone='neutral'}:{label:string;value:string;icon:typeof DollarSign;tone?:'green'|'red'|'neutral'}){const styles={green:'bg-brand-50 text-brand-600',red:'bg-red-50 text-red-600',neutral:'bg-slate-100 text-slate-600'};return <div className="card p-3 sm:p-4"><div className="flex items-start justify-between gap-2"><span className="text-xs text-slate-500 sm:text-sm">{label}</span><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${styles[tone]}`}><Icon size={16}/></span></div><p className="mt-3 text-lg font-bold break-words sm:mt-4 sm:text-xl">{value}</p></div>}
export function DashboardPage(){const payroll=employees.reduce((s,e)=>s+calculatePayroll(e,shifts,'2026-09',22),0);const summary=calculateSummary(transactions,payroll,7,shifts,0);return <><Title title="Главная"><button className="btn"><SlidersHorizontal size={16}/>Настроить экран</button></Title><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Доход" value={rubles(summary.income)} icon={TrendingUp} tone="green"/><Metric label="Расходы" value={rubles(summary.expenses)} icon={TrendingDown} tone="red"/><Metric label="Зарплаты" value={rubles(summary.payroll)} icon={Users}/><Metric label="Налог" value={rubles(summary.tax)} icon={DollarSign}/><Metric label="Чистая прибыль" value={rubles(profit(summary))} icon={TrendingUp} tone="green"/><Metric label="Смен завершено" value={String(summary.shifts)} icon={CheckCircle2}/></div><div className="mt-4 grid gap-4 sm:mt-5 sm:gap-5 lg:grid-cols-[1.55fr_1fr]"><section className="card min-w-0 p-4 sm:p-5"><h2 className="font-semibold">Доходы по дням</h2><div className="mt-6 flex h-40 items-end gap-1 sm:h-52 sm:gap-2">{[40,58,42,78,60,95,70,55,84,66,50,74].map((v,i)=><div key={i} className="flex min-w-0 flex-1 flex-col justify-end"><div className="rounded-t bg-brand-500/85" style={{height:`${v}%`}}/><span className="mt-2 text-center text-[10px] text-slate-400">{i+1}</span></div>)}</div></section><section className="card min-w-0 p-4 sm:p-5"><h2 className="font-semibold">Требуют внимания</h2><div className="mt-4 space-y-3"><div className="flex gap-3 rounded-lg bg-amber-50 p-3 text-sm"><CircleAlert className="shrink-0 text-amber-600" size={18}/><div><b>Удержание WB</b><p className="text-slate-600">3 730 ₽ · Подмена товара</p></div></div><div className="flex gap-3 rounded-lg bg-slate-50 p-3 text-sm"><CalendarIcon/><div><b>Завтрашняя смена</b><p className="text-slate-600">Максим · 08:00–22:00</p></div></div></div></section></div></>}
function CalendarIcon(){return <CheckCircle2 className="shrink-0 text-brand-600" size={18}/>
}
export function EmployeesPage(){return <><Title title="Сотрудники"><button className="btn btn-primary"><Plus size={16}/>Добавить сотрудника</button></Title><div className="card overflow-hidden"><div className="hidden grid-cols-[1.4fr_1fr_1fr_1fr_1fr] gap-3 border-b bg-slate-50 px-5 py-3 text-xs font-semibold text-slate-500 md:grid"><span>Сотрудник</span><span>Тип оплаты</span><span>Ставка</span><span>ПВЗ</span><span>Статус</span></div>{employees.map(e=><div key={e.id} className="grid gap-1.5 border-b px-4 py-4 last:border-0 sm:px-5 md:grid-cols-[1.4fr_1fr_1fr_1fr_1fr] md:items-center md:gap-3"><div className="min-w-0"><b>{e.fullName}</b><p className="text-xs text-slate-500">{e.phone}</p></div><span className="text-sm"><i className="mr-1 not-italic text-slate-500 md:hidden">Оплата:</i>{e.paymentType==='SHIFT'?'За смену':e.paymentType==='HOURLY'?'Почасовая':'Оклад'}</span><span className="text-sm"><i className="mr-1 not-italic text-slate-500 md:hidden">Ставка:</i>{rubles(e.rateKopecks)}{e.paymentType==='HOURLY'?' / час':''}</span><span className="text-sm"><i className="mr-1 not-italic text-slate-500 md:hidden">ПВЗ:</i>Кооперативная 93</span><span className="mt-1 md:mt-0"><i className="rounded-full bg-brand-50 px-2 py-1 text-xs not-italic text-brand-600">Активен</i></span></div>)}</div></>}
export function ShiftsPage(){return <><Title title="Смены"><button className="btn btn-primary"><Plus size={16}/>Создать смену</button></Title><div className="card overflow-hidden"><div className="border-b p-4 sm:p-5"><h2 className="font-semibold">Сентябрь 2026</h2><p className="text-sm text-slate-500">Календарь графика и фактических выходов</p></div><div className="divide-y">{shifts.map(s=>{const e=employees.find(x=>x.id===s.employeeId)!;return <div key={s.id} className="flex flex-wrap items-center gap-x-4 gap-y-2 p-4 sm:gap-x-8 sm:p-5"><b className="w-full sm:w-auto sm:min-w-36">{s.startsAt.slice(8,10)} сентября</b><span>{e.fullName}</span><span className="text-sm text-slate-500">08:00–22:00</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{status[s.status]}</span><button className="ml-auto py-1 text-sm font-medium text-brand-600">Заменить</button></div>})}</div></div></>}
export function FinancePage(){const [show,setShow]=useState(false);const [amount,setAmount]=useState('');const preview=useMemo(()=>amount?rubles(Math.round(Number(amount)*100)):'—',[amount]);return <><Title title="Финансы"><button className="btn btn-primary" onClick={()=>setShow(true)}><Plus size={16}/>Добавить запись</button></Title>{show&&<div className="card mb-5 p-4 sm:p-5"><h2 className="font-semibold">Новый доход или расход</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><label><span className="label">Сумма, ₽</span><input autoFocus inputMode="decimal" className="field" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label><label><span className="label">Тип</span><select className="field"><option>Доход</option><option>Расход</option></select></label><label><span className="label">Категория</span><input className="field" placeholder="Например, аренда"/></label></div><div className="mt-4 flex flex-wrap items-center gap-3"><button className="btn btn-primary flex-1 sm:flex-none" onClick={()=>setShow(false)}>Сохранить {preview}</button><button className="btn flex-1 sm:flex-none" onClick={()=>setShow(false)}>Отмена</button></div></div>}<div className="grid gap-4 sm:gap-5 lg:grid-cols-2"><TransactionList title="Доходы" rows={transactions.filter(x=>x.kind==='INCOME')}/><TransactionList title="Расходы" rows={transactions.filter(x=>x.kind==='EXPENSE')}/></div></>}
function TransactionList({title,rows}:{title:string;rows:Transaction[]}){return <section className="card min-w-0 p-4 sm:p-5"><h2 className="font-semibold">{title}</h2><div className="mt-3 divide-y">{rows.map(x=><div className="flex items-center justify-between gap-3 py-3" key={x.id}><div className="min-w-0"><b className="text-sm">{x.category}</b><p className="truncate text-xs text-slate-500">{x.date} · Кооперативная 93</p></div><span className={`shrink-0 whitespace-nowrap ${x.kind==='INCOME'?'font-semibold text-brand-600':'font-semibold'}`}>{rubles(x.amountKopecks)}</span></div>)}</div></section>}
const modules=['employees','shifts','salary','income','expenses','taxes','penalties','wb_deductions','telegram','analytics']
export function ModulesPage(){const [active,setActive]=useState(new Set(modules));return <><Title title="Настройки модулей"/><div className="card divide-y">{modules.map(m=><label key={m} className="flex items-center justify-between gap-4 px-4 py-4 sm:px-5"><div className="min-w-0"><b>{({employees:'Сотрудники',shifts:'Смены',salary:'Зарплаты',income:'Доходы',expenses:'Расходы',taxes:'Налоги',penalties:'Штрафы',wb_deductions:'Удержания WB',telegram:'Telegram',analytics:'Аналитика'} as Record<string,string>)[m]}</b><p className="mt-1 text-sm text-slate-500">Включает раздел, формы и виджеты Dashboard.</p></div><input type="checkbox" className="h-5 w-5 shrink-0 accent-green-600" checked={active.has(m)} onChange={()=>setActive(x=>{const n=new Set(x);n.has(m)?n.delete(m):n.add(m);return n})}/></label>)}</div></>}
function PickupPointsManual(){const [name,setName]=useState('');const [address,setAddress]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{await createPickupPoint({name,address,timezone:'Europe/Moscow'});setMessage('ПВЗ добавлен и сохранён.');setName('');setAddress('')}catch(error){setMessage(error instanceof Error?error.message:'Не удалось сохранить ПВЗ')}finally{setSaving(false)}}return <div className="card mx-auto max-w-2xl p-4 sm:p-6"><h1 className="text-xl font-bold sm:text-2xl">Пункты выдачи</h1><p className="mt-1 text-sm text-slate-500">Добавьте каждую рабочую точку вручную. Позже к ней можно привязать сотрудников и смены.</p><form className="mt-5 grid gap-4" onSubmit={save}><label><span className="label">Название ПВЗ</span><input className="field" required value={name} onChange={e=>setName(e.target.value)} placeholder="Кооперативная 93"/></label><label><span className="label">Адрес</span><input className="field" required value={address} onChange={e=>setAddress(e.target.value)} placeholder="г. Грозный, ул. Кооперативная, 93"/></label><label><span className="label">Часовой пояс</span><input className="field" value="Europe/Moscow" readOnly/></label><button className="btn btn-primary w-full sm:w-auto sm:justify-self-start" disabled={saving}>{saving?'Сохраняем…':'Добавить ПВЗ'}</button></form>{message&&<p className="mt-4 text-sm text-brand-600">{message}</p>}</div>}
export function SoonPage({title,description}:{title:string;description:string}){if(title==='Пункты выдачи')return <PickupPointsManual/>;const [sent,setSent]=useState(false);return <div className="card mx-auto max-w-2xl p-6 text-center sm:p-8"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-brand-50 text-brand-600"><CircleAlert/></div><h1 className="mt-4 text-xl font-bold sm:text-2xl">{title}</h1><p className="mx-auto mt-3 max-w-lg text-slate-500">{description}</p><button className="btn btn-primary mt-6" onClick={()=>setSent(true)}>{sent?'Заявка принята':'Хочу ранний доступ'}</button></div>}

export function TelegramPage(){
  const [integration,setIntegration]=useState<TelegramIntegrationInfo|null>(null)
  const [token,setToken]=useState('')
  const [code,setCode]=useState<string>()
  const [error,setError]=useState<string>()
  const [loading,setLoading]=useState(true)
  useEffect(()=>{getTelegramIntegration().then(setIntegration).catch(e=>setError(e instanceof Error?e.message:'Не удалось загрузить подключение')).finally(()=>setLoading(false))},[])
  async function saveBot(){setLoading(true);setError(undefined);try{const result=await connectTelegramBot(token);setIntegration({id:'',status:'CONNECTED',bot_username:result.bot.username,last_error:null});setToken('')}catch(e){setError(e instanceof Error?e.message:'Не удалось подключить бота')}finally{setLoading(false)}}
  async function makeCode(){setLoading(true);setError(undefined);try{setCode(await createTelegramPairingCode())}catch(e){setError(e instanceof Error?e.message:'Не удалось создать код')}finally{setLoading(false)}}
  async function disconnect(){setLoading(true);setError(undefined);try{await disconnectTelegramBot();setIntegration(null);setCode(undefined)}catch(e){setError(e instanceof Error?e.message:'Не удалось отключить бота')}finally{setLoading(false)}}
  const connected=integration?.status==='CONNECTED'
  return <><Title title="Telegram-бот"/><section className="card max-w-2xl p-4 sm:p-6"><h2 className="font-semibold">Быстрые действия с телефона</h2><p className="mt-2 text-sm text-slate-500">Подключите собственного бота организации. Token проверяется на сервере, сохраняется зашифрованно, а webhook регистрируется автоматически.</p>{connected?<div className="mt-5 rounded-xl border border-brand-200 bg-brand-50 p-4"><p className="font-semibold text-brand-800">@{integration.bot_username} подключён</p><p className="mt-1 text-sm text-brand-700">Бот готов добавлять удержания и расходы, показывать сотрудников и смены.</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-primary" disabled={loading} onClick={makeCode}>Получить код для /start</button><button className="btn" disabled={loading} onClick={disconnect}>Отключить бота</button></div></div>:<div className="mt-5"><label><span className="label">Token от BotFather</span><input type="password" autoComplete="off" className="field" value={token} onChange={e=>setToken(e.target.value)} placeholder="123456789:AA..."/></label><button className="btn btn-primary mt-3" disabled={loading||!token.trim()} onClick={saveBot}>{loading?'Проверяем…':'Подключить бота'}</button></div>}<div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-medium">Кнопки бота</p><p className="mt-2 text-slate-600">➕ Удержание · ➕ Расход · 👥 Сотрудники · 📅 Смены</p></div>{code&&<div className="mt-5 rounded-xl border border-brand-200 bg-brand-50 p-4"><p className="text-sm text-brand-800">Отправьте подключённому боту это сообщение в течение 15 минут:</p><code className="mt-2 block break-all select-all text-lg font-bold tracking-[.15em] text-brand-700 sm:text-xl sm:tracking-[.2em]">/start {code}</code></div>}{integration?.status==='ERROR'&&<p className="mt-3 text-sm text-red-600">{integration.last_error||'Ошибка подключения Telegram'}</p>}{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}</section></>
}
