create extension if not exists "pgcrypto";

create type public.member_role as enum ('OWNER','MANAGER','EMPLOYEE');
create type public.module_key as enum ('employees','shifts','salary','income','expenses','taxes','penalties','wb_deductions','telegram','analytics','valuable_items');
create type public.shift_status as enum ('PLANNED','ON_DUTY','COMPLETED','REPLACED','NO_SHOW');
create type public.payment_type as enum ('SHIFT','HOURLY','SALARY');
create type public.penalty_status as enum ('ASSIGNED','DISPUTED','CANCELLED','CONFIRMED','WITHHELD');
create type public.deduction_status as enum ('NEW','INVESTIGATING','DISPUTED','PENDING','CANCELLED_BY_WB','CONFIRMED_BY_WB','EMPLOYEE_LIABILITY','OWNER_LOSS');

create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text, onboarding_completed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null check(length(name)>1), currency text not null default 'RUB', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, user_id uuid references auth.users on delete cascade, employee_id uuid, role public.member_role not null, permissions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(organization_id,user_id));
create table public.pickup_points (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, internal_name text, address text not null, timezone text not null default 'Europe/Moscow', working_hours jsonb not null default '{}'::jsonb, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.employees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, full_name text not null, phone text, telegram_username text, payment_type public.payment_type not null default 'SHIFT', status text not null default 'ACTIVE' check(status in ('ACTIVE','ARCHIVED')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.organization_members add constraint member_employee_fk foreign key(employee_id) references public.employees on delete set null;
create table public.employee_pickup_points (employee_id uuid not null references public.employees on delete cascade, pickup_point_id uuid not null references public.pickup_points on delete cascade, created_at timestamptz not null default now(), primary key(employee_id,pickup_point_id));
create table public.salary_rules (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, employee_id uuid not null references public.employees on delete cascade, payment_type public.payment_type not null, rate_kopecks bigint not null check(rate_kopecks>=0), effective_from date not null, monthly_norm_days integer check(monthly_norm_days > 0), created_at timestamptz not null default now(), unique(employee_id,effective_from));
create table public.shifts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pickup_point_id uuid not null references public.pickup_points, employee_id uuid not null references public.employees, planned_start timestamptz not null, planned_end timestamptz not null, actual_start timestamptz, actual_end timestamptz, status public.shift_status not null default 'PLANNED', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(planned_end > planned_start), check(actual_end is null or actual_start is null or actual_end > actual_start));
create index shifts_org_period_idx on public.shifts(organization_id, planned_start);
create table public.shift_changes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, shift_id uuid not null references public.shifts on delete cascade, previous_employee_id uuid references public.employees, new_employee_id uuid references public.employees, reason text, changed_by uuid references auth.users, created_at timestamptz not null default now());
create table public.shift_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, employee_id uuid not null references public.employees, pickup_point_id uuid not null references public.pickup_points, pattern jsonb not null, starts_at time not null, ends_at time not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.bonuses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, employee_id uuid not null references public.employees, date date not null, amount_kopecks bigint not null check(amount_kopecks>0), comment text, created_at timestamptz not null default now());
create table public.employee_penalties (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, employee_id uuid not null references public.employees, pickup_point_id uuid references public.pickup_points, date date not null, amount_kopecks bigint not null check(amount_kopecks>0), reason text not null, comment text, status public.penalty_status not null default 'ASSIGNED', created_by uuid references auth.users, created_at timestamptz not null default now());
create table public.salary_periods (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, starts_on date not null, ends_on date not null, status text not null default 'OPEN' check(status in ('OPEN','CLOSED')), closed_at timestamptz, unique(organization_id,starts_on,ends_on), check(ends_on>=starts_on));
create table public.salary_accruals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, salary_period_id uuid not null references public.salary_periods, employee_id uuid not null references public.employees, amount_kopecks bigint not null, calculation jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(salary_period_id,employee_id));
create table public.salary_payments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, employee_id uuid not null references public.employees, date date not null, amount_kopecks bigint not null check(amount_kopecks>0), kind text not null check(kind in ('ADVANCE','PAYMENT','ADJUSTMENT')), comment text, created_at timestamptz not null default now());
create table public.income_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pickup_point_id uuid not null references public.pickup_points, date date not null, category text not null, amount_kopecks bigint not null check(amount_kopecks>0), description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.expense_categories (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, name text not null, color text, archived_at timestamptz, unique(organization_id,name));
create table public.expense_entries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pickup_point_id uuid references public.pickup_points, category_id uuid references public.expense_categories, date date not null, amount_kopecks bigint not null check(amount_kopecks>0), description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recurring_expenses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pickup_point_id uuid references public.pickup_points, category_id uuid references public.expense_categories, amount_kopecks bigint not null check(amount_kopecks>0), frequency text not null check(frequency in ('MONTHLY')), day_of_month integer not null check(day_of_month between 1 and 31), description text, active boolean not null default true, created_at timestamptz not null default now());
create table public.tax_settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations on delete cascade, rate numeric(5,2) not null default 0 check(rate between 0 and 100), enabled boolean not null default false, updated_at timestamptz not null default now());
create table public.wb_deductions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pickup_point_id uuid references public.pickup_points, event_at timestamptz, amount_kopecks bigint not null check(amount_kopecks>0), reason text not null, status public.deduction_status not null default 'NEW', shift_id uuid references public.shifts, employee_id uuid references public.employees, comment text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.wb_deduction_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, deduction_id uuid not null references public.wb_deductions on delete cascade, event_type text not null, note text, actor_id uuid references auth.users, created_at timestamptz not null default now());
create table public.enabled_modules (organization_id uuid not null references public.organizations on delete cascade, module public.module_key not null, enabled boolean not null default true, updated_at timestamptz not null default now(), primary key(organization_id,module));
create table public.dashboard_widgets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, user_id uuid not null references auth.users on delete cascade, widget_key text not null, enabled boolean not null default true, position integer not null default 0, unique(organization_id,user_id,widget_key));
create table public.notification_settings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, pickup_point_id uuid references public.pickup_points, settings jsonb not null default '{}'::jsonb, unique(organization_id,pickup_point_id));
create table public.telegram_integrations (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations on delete cascade, status text not null default 'NOT_CONNECTED', created_at timestamptz not null default now());
create table public.early_access_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, user_id uuid not null references auth.users, feature text not null default 'valuable_items', created_at timestamptz not null default now(), unique(organization_id,user_id,feature));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations on delete cascade, actor_id uuid references auth.users, entity_type text not null, entity_id uuid, action text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.subscriptions (id uuid primary key default gen_random_uuid(), organization_id uuid not null unique references public.organizations on delete cascade, plan text not null default 'TRIAL' check(plan in ('TRIAL','START','PRO','BUSINESS')), trial_ends_at timestamptz, status text not null default 'ACTIVE', created_at timestamptz not null default now());

create or replace function public.is_org_member(org_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from organization_members where organization_id=org_id and user_id=auth.uid()) $$;
create or replace function public.is_org_owner(org_id uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from organization_members where organization_id=org_id and user_id=auth.uid() and role='OWNER') $$;
revoke all on function public.is_org_member(uuid), public.is_org_owner(uuid) from public;
grant execute on function public.is_org_member(uuid), public.is_org_owner(uuid) to authenticated;

-- Direct browser access is restricted to an authenticated member of the row's organization.
do $$ declare t text; begin foreach t in array array['pickup_points','employees','salary_rules','shifts','shift_changes','shift_templates','bonuses','employee_penalties','salary_periods','salary_accruals','salary_payments','income_entries','expense_categories','expense_entries','recurring_expenses','tax_settings','wb_deductions','wb_deduction_events','enabled_modules','dashboard_widgets','notification_settings','telegram_integrations','early_access_requests','audit_logs','subscriptions'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy org_select on public.%I for select to authenticated using (public.is_org_member(organization_id))',t); execute format('create policy org_write on public.%I for all to authenticated using (public.is_org_owner(organization_id)) with check (public.is_org_owner(organization_id))',t); end loop; end $$;
alter table public.organizations enable row level security;
create policy organization_select on public.organizations for select to authenticated using(public.is_org_member(id));
create policy organization_create on public.organizations for insert to authenticated with check(true);
create policy organization_owner_update on public.organizations for update to authenticated using(public.is_org_owner(id)) with check(public.is_org_owner(id));
alter table public.organization_members enable row level security;
create policy members_select on public.organization_members for select to authenticated using(public.is_org_member(organization_id));
create policy members_owner_write on public.organization_members for all to authenticated using(public.is_org_owner(organization_id)) with check(public.is_org_owner(organization_id));
alter table public.profiles enable row level security;
create policy own_profile on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
alter table public.employee_pickup_points enable row level security;
create policy employee_point_read on public.employee_pickup_points for select to authenticated using(exists(select 1 from public.employees e where e.id=employee_id and public.is_org_member(e.organization_id)));
create policy employee_point_owner on public.employee_pickup_points for all to authenticated using(exists(select 1 from public.employees e where e.id=employee_id and public.is_org_owner(e.organization_id))) with check(exists(select 1 from public.employees e where e.id=employee_id and public.is_org_owner(e.organization_id)));

create or replace function public.replace_shift(p_shift_id uuid,p_employee_id uuid,p_reason text) returns void language plpgsql security definer set search_path=public as $$ declare old_employee uuid; org uuid; begin select organization_id,employee_id into org,old_employee from shifts where id=p_shift_id for update; if not public.is_org_owner(org) then raise exception 'forbidden'; end if; update shifts set employee_id=p_employee_id,status='REPLACED',updated_at=now() where id=p_shift_id; insert into shift_changes(organization_id,shift_id,previous_employee_id,new_employee_id,reason,changed_by) values(org,p_shift_id,old_employee,p_employee_id,p_reason,auth.uid()); end $$;
